### ISSUE TITLE
Add some visual indication of service restart

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-PHAL-plugin-system#6]
Is there some method to display a GUI page that stays active while the core services are stopping to indicate the system is restarting (and maybe shutdown/restart)? Currently, it isn't immediately clear that requests to shutdown/restart/restart services are handled.

https://github.com/OpenVoiceOS/ovos-PHAL-plugin-system/blob/dev/ovos_PHAL_plugin_system/__init__.py#L61

**Comment by JarbasAl** [comment]
you can import SkillGUI class from ovos_utils and add a GUI to the plugin, see the wifi plugins for an example of using GUI in a PHAL plugin
